### ISSUE TITLE
ffffm-button-bind: Option to dis-/enable Client Network

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#15]

**Comment by oszilloskop** [comment]
Wir haben dieses Feature nicht umgesetzt, weil es bei uns keine Bedarfe dafür gibt, und weil wir nicht wissen, wie wir folgende Zustände nur mit einer LED (der Wifi-LED) anzeigen können:

1) Client ON / Mesh ON
2) Client OFF / Mesh ON
3) Client OFF / Mesh OFF ( -> also Wifi ausgeschaltet)

**Comment by rubo77** [comment]
Vielleicht so:

An/blinken/aus

**Comment by oszilloskop** [comment]
Durch das Package wird nur die Dimmung der LEDs manipuliert.
In die Ansteuer-Logik der LED wird nicht eingegriffen.
Daher ist bei der Wifi-LED der Zustand 'An' das Problem, weil die Blinkt (meistens).

**Comment by rubo77** [comment]
Naja, man muss das ja auch nicht anzeigen.

Dass das Client Netz an oder aus ist, merkt man ja im Network Manager
