### ISSUE TITLE
Is this working with 802.11s?

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#16]
https://github.com/freifunk-ffm/packages/blob/master/ffffm-button-bind/files/etc/rc.button/rfkill.btnb#L11

This looks like not

**Comment by oszilloskop** [comment]
Die drei Zeilen sind L11-L13 sind dazu da, damit der Wifi-Treiber wirklich/absolut/ganz sicher neu gestartet wird. 

Eigentlich würde https://github.com/freifunk-ffm/packages/blob/master/ffffm-button-bind/files/etc/rc.button/rfkill.btnb#L13 schon reichen.

**Comment by rubo77** [comment]
pr: #21
