### ISSUE TITLE
why manually add  /etc/config/button-bind ?

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#17]
I added this as file in the package: https://github.com/rubo77/ffm-packages/commit/72b9a4376cd33cad6f42aa3a775130e6d35bce66

would that give any problems?

**Comment by oszilloskop** [comment]
Bei uns wurde eine solche Config-Datei nicht in das Package aufgenommen, weil wir uns Tests bezüglich Upgrade/Update sparen wollten. 
Ist die Config nicht im Package, wird auch nix ausversehen überschrieben :o)

**Comment by rubo77** [comment]
Ok, das sollte man Mal verbessern

**Comment by christf** [comment]
Wenn du magst, hau rein. Wir freuen uns über Verbesserungen. 

Am 22. Juli 2017 12:33:01 MESZ schrieb Ruben Barkow <notifications@github.com>:
>Ok, das sollte man Mal verbessern
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/freifunk-ffm/packages/issues/17#issuecomment-317174406

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
