### ISSUE TITLE
was heisst start=97?

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#18]
https://github.com/freifunk-ffm/packages/blob/master/ffffm-button-bind/files/etc/init.d/button-bind#L2

**Comment by oszilloskop** [comment]
Ohje, das ist lange her, habe mir irgendein Package als Template genommen, welches auch über den init.d Prozess nach/beim Booten gestartet wird. 
Hmm, keine Ahnung mehr....

**Comment by oszilloskop** [comment]
Das hat was mit der Reihenfolge der init.d Aufrufe zu tun. Es muss muss sicher gestellt sein, dass während des Bootvorgangs über die Dimmung der LEDs erst entschieden wird, wenn die Ansteuerung der LEDs schon durch ist.

Ansonsten wird die Dimmung einfach wieder überschrieben.

**Comment by rubo77** [comment]
Aber die Variable da an der Stelle macht keinen Sinn, oder?

Das wird ja über Den Dateinamen geregelt
