### ISSUE TITLE
müsste das nicht nur moven, wenn noch nicht existiert?

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#19]
https://github.com/freifunk-ffm/packages/blob/master/ffffm-button-bind/files/lib/gluon/upgrade/888-button-bind#L4

Es sieht mir so aus, als wenn das beim 2. Firmware Update mit diesem Paket dann einen Fehler macht

**Comment by oszilloskop** [comment]
Oh, ja, dass geht in die Hose :o(
Habe das gemacht um die original Datei irgendwo zu behalten. Das ist aber eigentlich nicht notwendig. 

Das Problem sollte mit einem einfache `rm rfkill` anstelle des `mv rfkill rfkill.owrt` zu lösen sein (auch bei/nach weiteren Updates).

**Comment by oszilloskop** [comment]
**Ich erzähle Quatsch!!**
`rfkill.owrt` wird ja noch aufgerufen. 
Klar, dass muss nur verschoben werden, wenn `rfkill.owrt`  noch nicht existiert.

**Comment by rubo77** [comment]
Also ein Bug.

**Comment by rubo77** [comment]
Vielleicht ist das auch OK so. anscheinend wird das rfkill script ja bei jedem firmware upgrade wieder hergestellt. dann wäre das korrekt, wenn man das jedes mal umbenennt.

**Comment by oszilloskop** [comment]
Stimmt.
Close.
