### ISSUE TITLE
ffffm-button-bind: ubus nutzen um das Interface zu bestimmen

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#22]
aus: https://github.com/freifunk-ffm/packages/pull/21/commits/985023d936d18ac13e39016577896c5ffc2db176

    DEV="$(iw dev|grep Interface|grep -e 'mesh0' -e 'ibss0'| awk '{ print $2 }'|head -1)"
	

> christ
> 
> Hier sollte ubus nach dem Gerät gefragt werden. Im gluon-l3roamd initscript ist ein Beispiel
> 
> rubo77
> 
> welches meinst du? Ich habe dies ausprobiert im Router, aber das geht wohl nicht so einfach:
> https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-l3roamd/files/etc/init.d/gluon-l3roamd#L13
> 
> die Zeile 10 funktioniert aber gut mit dem DEV=...
> 

aus dem chat:

> 
> Klaus_Dieter (IRC)
> der kam von mir :)
> ah, der jsonfilter passt nicht auf den anwendungsfall.
> 
> ubus call network.interface dump. dann solltest du die radios finden

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
