### ISSUE TITLE
ffffm-button-bind: Teil auslagern, sodass nicht das Paket selbst sondern zusätzliche scripte die Funktionalität bereitstellen

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#23]
aus https://github.com/freifunk-ffm/packages/pull/20/commits/3c2d2b81e437dacc140e1e88670a80b4c40caded und https://github.com/freifunk-ffm/packages/pull/20#issuecomment-317590499

>  @christf  
> Wie lässt sich dieser Teil auslagern, sodass nicht das Paket selbst sondern zusätzliche scripte die Funktionalität bereitstellen?
> 
> @oszilloskop  
> Das wird schwer. Nicht nur die Funktionalität muß modular erweitert werden können, sondern auch die Texte im Router-Konfig-Modus. Weil dort wird u.a. die Ersteinstellung durchgeführt.
> 

>  Das müsste schon gehen. Die scripte kann man in. /etc/buttonscripte.d ablegen und die Texte nach man per lua erzeugen lassen und sourcen.  Ob man das ganze dann implizit über Dateinamen matcht oder noch einen geschickteren Mechanismus findet ist sicher noch eine Frage. 

> christf
> Da jetzt noch irgend einen Parser zur Laufzeit reinbringen...hmm?
> Schön wäre das schon, weil ich immer noch nicht weiß, ob dass Abschalten der Client ohne irgendeinen optischen Indikator nicht zu mehr Problemen führt, als es denn nutzt. Auch ist das abschalten der Clients zur Zeit nur für radio0 realisiert. Keine Ahnung was da bei Dualband-Routern passiert.
> 
> Wir gehen das mal später an, das mit dem Modularen.
> 

siehe auch #24

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.

**Comment by rubo77** [comment]
diskussion wird hier fortgesetzt: https://github.com/rubo77/ffm-packages/issues/12
