### ISSUE TITLE
ffffm-button-bind: Texte im Router-Konfig-Modus in i18n

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#24]
Also english should be added

**Comment by oszilloskop** [comment]
Das hatte ich versucht. Habe da eigentlich auch Erfahrung mit, aber bei diesem Package liegt/lag irgendwas quer. Habe nach einem Tag aufgegeben.

**Comment by oszilloskop** [comment]
Kurz noch die Information, dass dieses Package u.a. auch für Gluon 2016.2.x entwickelt wurde.
Es wurden und werden daher funktionelle wie auch beschreibende Kompromisse bezüglich des knappen Flash-Speichers bei 4MB-Routern eingegangen.

P.S.
Ich habe hier nämlich auf meinem Router noch I2C-Module zum nachladen, und die passen zur Zeit gerade noch ebenso in den Flash-Speicher :o).
Da ist dann jedes zusätzliche Byte in diesem Package zweimal umzudrehen.

**Comment by rubo77** [comment]
Dann am besten luaSrcdiet anwenden

Und shellDiet.sh

**Comment by oszilloskop** [comment]
Wir setzen ja schon GluonSrcDiet ein:
https://github.com/freifunk-ffm/packages/blob/master/ffffm-button-bind/Makefile#L31

Nur das nutzt bei Spracherweiterungen nicht wirklich :o)

**Comment by christf** [comment]
Ich bin nicht so sehr von der Wirksamkeit der minifier überzeugt, dass ich für sh einen neuen einführen wollen würde. Das rootfs ist gepackt und es ist mir nicht klar ob ein zum zip zusätzlicher minifier überhaupt einen Einfluss auf die Größe der Daten im Image hat. 
Gegen minifier spricht die durch diese eingeführte  Komplexität und die daraus resultierende  schlechte Lesbarkeit der durch sie behandelten scripte im Image. 

Hat jemand Belege für die imagegröße mit und ohne minifier? 

Am 25. Juli 2017 21:44:02 MESZ schrieb Ruben Barkow <notifications@github.com>:
>Dann am besten luaSrcdiet anwenden
>
>Und shellDiet.sh
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/freifunk-ffm/packages/issues/24#issuecomment-317850455

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rubo77** [comment]
@adorfer hat den glounShellDiet.sh von mir auch in den Eulenfunk packages eingebaut, der nur die Kommentare löscht, das bringt schon was

**Comment by christf** [comment]
Wie groß ist ein Image ohne gluonshelldiet und wie groß ist es mit identischen Paketen und mit gluonshelldiet? 

Am 26. Juli 2017 16:57:33 MESZ schrieb Ruben Barkow <notifications@github.com>:
>@adorfer hat den glounShellDiet.sh von mir auch in den Eulenfunk
>packages eingebaut, der nur die Kommentare löscht, das bringt schon was
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/freifunk-ffm/packages/issues/24#issuecomment-318079465

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Adorfer** [comment]
mir wäre irgendein "globales" shell-diet-paket" lieb, was nur einmal eingebunden wird. 
Und sich während des Builds um alle Pakete kümmert. Vermutlich wäre das aber eher ein Gluon-Buildscript-patch...

BTW: lua-scripte könnte man auch auf Kommentarzeilen filterrn. 
(Und ja... ich warte noch drauf, dass jemand "false positives" bringt wo ein script auf Multiline-statements filtert oder aber ein script, was Daten aus den eigenen Kommentarzeilen ausliest und parsed....)

**Comment by rubo77** [comment]
@Adorfer, du meintest doch Mal dass du Dank GluonSrcDiet.sh Erin kleineres Image erstellen könntest, oder?

Außerdem ist es auch angenehm, wenn man schon viele Kommentare in seinem Code packen kann.

**Comment by Adorfer** [comment]
Ich könnte in einer Domain damit wieder DIR615 bauen. Nur L2TP passt da auch nicht, war also wirklich auf des Messers Schneide.

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
