### ISSUE TITLE
ffffm-button-bind: Default Value in site.conf defined

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#25]
It should be possible to define the default state of all routers in your site.conf

**Comment by oszilloskop** [comment]
Default ist immer '0' -> "Wifi-Button wie gehabt".
Alles andere sind ja Ausnahmen und wird nur im Extremfalle genutzt.

**Comment by rubo77** [comment]
wäre aber schön, wenn man den button in seiner community per default deaktivieren könnte und leute sich den nur bei bedarf im config mode aktivieren könnten.

> Kein normaluser braucht den wifi button im normalfall

**Comment by oszilloskop** [comment]
Okay, da hast Du recht. Der Default-Modus "nix machen" ist ein Argument.

**Comment by rubo77** [comment]
im Nord master branch ist dies nun default: https://github.com/rubo77/ffm-packages/commit/0067a77a01c00607e0f01d7f2353d8603649a3ad

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
