### ISSUE TITLE
ffffm-button-bind: LED switch statt hold

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#26]
ich finde es sinnvoller, wenn man den night modus im laufenden Betrieb an und abschalten kann, das habe ich im Nord Branch wiederhergestellt: https://github.com/rubo77/ffm-packages/commit/80a66634bbb8cc22df7b20178fe1f7fe47f1d257

(vorrausgesetzt ich habe die änderung richtig verstanden)

vielleicht könnte man das irgendwie konfigurierbar machen?

oder zwei optionen, eine macht die LEDs nur an, während man draufdrückt und eine, ganz an oder ganz aus.

warum habt ihr euch für das onclick entschieden?

**Comment by christf** [comment]
Die Überlegung war, dass man ohnehin nur die led sehen kann, während man vorm Gerät ist. Dann reicht es die LED nur dann zu aktivieren während man drückt. 

Am 4. August 2017 01:15:03 MESZ schrieb Ruben Barkow <notifications@github.com>:
>ich finde es sinnvoller, wenn man den night modus im laufenden Betrieb
>an und abschalten kann, das habe ich im Nord Branch wiederhergestellt:
>https://github.com/rubo77/ffm-packages/commit/80a66634bbb8cc22df7b20178fe1f7fe47f1d257
>
>(vorrausgesetzt ich habe die änderung richtig verstanden)
>
>vielleicht könnte man das irgendwie konfigurierbar machen?
>
>oder zwei optionen, eine macht die LEDs nur an, während man draufdrückt
>und eine, ganz an oder ganz aus.
>
>warum habt ihr euch für das onclick entschieden?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/freifunk-ffm/packages/issues/26

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by oszilloskop** [comment]
Unsere Umsetzung sollte nie ein schaltbarer "**Nacht**-Modus" werden. (Schaltbetrieb)

Mit unsere Umsetzung werden die LED nur für die Zeit des Drückens des Tasters eingeschaltet.(Tastbetrieb).
Unsere Motivation sind Akku/Solar-betriebene Router. Nach jedem Booten sind die LED sofort deaktiviert und es wird dadurch sofort Energie gespart. 

Die von Dir gewünschte "LED-Schaltfunktion" müsste neben der "LED-Tastfunktion" neu aufgesetzt werden. Das bläht das Package weiter auf. Es müßte u.a. gespeichert werden, welcher Zustand momentan aktiv ist, und somit beim nächsten Booten wieder aktiviert werden soll, etc.

**Comment by rubo77** [comment]
Ich finde es ok, Wenn die nach den Booten immer wieder aus sind, dann wäre das auch für die stromsparende Version ausreichend.

Aber ich schau Mal, ob man da mit wenig teilen in eine extra Option setzen kann

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
