### ISSUE TITLE
ffffm-fastd-auto-mtu: Erfahrungen

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#27]
Könnt ihr mal berichten, wie gut das läuft?

Damit könnte man ja die MTU Option in der `site.conf` komplett weg lassen, wenn das upstream geht

**Comment by christf** [comment]
es lief gut bei uns.... die MTU-Option brauchte der PAtch aber immer noch.

Wir hatten das glaub ich länger im IRC besprochen. Ist die Frage noch aktuell?

**Comment by rubo77** [comment]
War geklärt. Könnte man hier​ jedoch Mal festhalten

**Comment by oszilloskop** [comment]
Das Package wird bei uns nicht mehr eingesetzt. Daher fehlen uns Erfahrungswerte mit Gluon 2017.x und 2018.x .
