### ISSUE TITLE
test vsyncWR841N(TPD)v9 LEDs aus schaltet die power leuchte nicht aus

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#28]
Bei einem WR841N(TPD)v9 funktioniert das ausschalten nicht komplett. Es hört zwar das Blinken der WIFI LED auf aber die Power-LED leuchtet weiter. heikel ist auch der 841v7 der keinen Wifi Button hat sondern nur einen QSS-Taster und einen vertieften reset knopf. Einige Modelle haben auch einen wifi-schalter statt Taster.

Es gibt ja auch einige Router, die gar keinen WiFi Taster haben. Ich denke es wäre sinnvoll, das Paket nur bei einigen getesteten TP-Link Modellen in die firmware einzubauen. Dies kann man ja in der site.mk steuern indem man das paket nicht in der Variablen `GLUON_SITE_PACKAGES` angbt sondern am Ende mit:

    ifeq ($(GLUON_TARGET),ar71xx-generic)
      GLUON_TLWR1043_SITE_PACKAGES := ffffm-button-bind
      GLUON_TLWR740_SITE_PACKAGES := ffffm-button-bind
      GLUON_TLWR741_SITE_PACKAGES := ffffm-button-bind
      GLUON_TLWR841_SITE_PACKAGES := ffffm-button-bind
      GLUON_TLWR842_SITE_PACKAGES := ffffm-button-bind
    endif

**Comment by oszilloskop** [comment]
Die Power-LED beim WR841 v9 ist hart verdrahtet. Daher ist diese nicht schaltbar.

Wie Du richtig schreibst kann jede Community selber entscheiden, bei welchen Routern das Package eingebunden wird. Ein Hinweis in der README.md wäre da dann hilfreich.

**Comment by rubo77** [comment]
Bei welchem Router Modellen habt ihr das denn erfolgreich getestet?

Falls der v7 Probleme machte, wir könnte man den in der Site. Mk ausschließen?

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
