### ISSUE TITLE
ffffm-button-bind: Option to disable mesh-VPN for some hours

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#29]
If you need your bandwidth alone for yourself for some hours, this would be helpful to have a button, to disable the VPN-Mesh-Uplink for some 5 hours and automatically re-enable it after that timeframe

At the moment this is only possible via SSH:

    ssh root@$router_ip '(/etc/init.d/fastd stop && sleep 18000 && /etc/init.d/fastd start)&'

see: https://forum.freifunk.net/t/mesh-vpn-fur-x-stunden-ausschalten/13627/7

**Comment by rubo77** [comment]
just stop, sleep and start fastd would not be enough, cause those triggers would sum up each time, you press the button again.

I think a second press on the button should stop the pause immediately and reenable fastd. 

my suggestion, to create a `fastd-pause.sh`-script and call that by the button-press:

    /etc/init.d/fastd stop && sleep 18000 && /etc/init.d/fastd start

1. check for running instance of `fastd-pause.sh`
2. if none, start  `fastd-pause.sh`
3. if exist, kill all running processes of `fastd-pause.sh` and restart fastd immediately with ``/etc/init.d/fastd start``

**Comment by oszilloskop** [comment]
The requirements and the gole aren't clear.
Why I shouldn't use the main power button for activities like that?

**Comment by rubo77** [comment]
if you use the power button, you have to restart the router by hand after some hours. Also you do not want to disable mesh-passtrrough usually, you only want to disable the mesh-VPN uplink via fastd or tunneldigger, so you have your bandwith for yourself alone for some time.

I had a neighbour, that unplugged the network kable for the uplink sometimes and forgot to plug it in when he was finished gaming.

**Comment by oszilloskop** [comment]
Just for my understanding: That means that user/clients which would like connect to your device will see a broken and not working Freifunk-Node during the "paused state". In addition if you are the only one uplink for your neighborhood routers then the whole mesh behind your paused router will not be work for any connected devices. Is that right?

**Comment by rubo77** [comment]
They will not see a broken Freifunk-Node unless you are the only uplink in your local mesh-cloud.

**Comment by rubo77** [comment]
I created a first version with two more options: 

- two different nightmodes
- mesh-vpn off for 5 hours

https://github.com/rubo77/ffm-packages/compare/0067a77a01...661ba0c872

**Comment by oszilloskop** [comment]
Should we encourage that kind of behavior? If people don't know it, then hopefully they will switch off their node.

**Comment by rubo77** [comment]
I think it is much less weird  if they switch it off only for 5 hours than switching it off for good.

It will not be the default, so this is an option for advanced users anyway.

I also thought about making the timeframe configurable, but that makes it to bloated.

**Comment by rubo77** [comment]
We could make this a hidden feature, that can be only activated on the console with uci

**Comment by rubo77** [comment]
Why is this kill -HUP not working?

https://github.com/rubo77/ffm-packages/commit/96905b36fdf0a2e3e83944081632b2ff1be7ba57#diff-e875efb3949b9bd2b8f30bfad7e49c8fR57

**Comment by oszilloskop** [comment]
Is it not working or is it not reached?
What about 
https://github.com/rubo77/ffm-packages/commit/96905b36fdf0a2e3e83944081632b2ff1be7ba57#diff-e875efb3949b9bd2b8f30bfad7e49c8fR55
Will the skript mesh-vpn-pause.sh block the main skript until it is be done?

**Comment by christf** [comment]
I do not like this feature for a number of reasons:
* what if the device resets, should it remember it was meant to be turned off?
* what if the mesh-vpn is the only connection to the internet for the local mesh?
* hidden features are in my experience better skipped altogether. there is much time & effort spent but only few if any people ever use it
* the use-case is sketchy. This feature addresses the fear of a user that freifunk might steal his bandwidth. but that never happens in the first place. And if it does, usually other solutions should be considered than turning it off.

**Comment by rubo77** [comment]
1. it should not remember the state
2. if it is the only connection for the local mesh, the local mesh will be cut off. This will be the same, as if the user unplugs the cable to the uplink, but less worse, because it will come back online after 5 hours automatically. 
3. you are right
4. In those places, where a user only has some MBit bandwidth I can thik of no other financial reasonable solution. The only solution for users in such places would be not to share their limited bandwidth at all, which would be a pity, especially if they are the only uplink in the local mesh. (This has happened at my friends home: https://mesh.freifunk.in-kiel.de/#!v:m;n:a0f3c1e56dac )

**Comment by rubo77** [comment]
@oszilloskop: it is reached, but the kill -HUP just kills the runniing (sleeping for 5h) process and it respawns with another PID immediately. 

I have to kill the sleeping process in another way, but how?

**Comment by rubo77** [comment]
This is solved in #31 what do you think by now?

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
