### ISSUE TITLE
Port-Nummer zuweisen zu MTU-size?

### ISSUE THREAD

**Issue by Adorfer** [freifunk-ffm/packages#3]
Vermutlich überlese ich etwas, aber wo definiere ich, welche Ports genutzt werden sollen abhängig von der gewählten MUT-size?
Und wie wäre es, 3-4 Größen anzugeben?
Ich würde sogar ggf. zwischen mehreren server-Einträgen (anderer Hosts9 wechseln zu können im Fall der Fälle.

**Comment by oszilloskop** [comment]
Die Ports werden nicht in Abhängigkeit der MTU definiert.
In Frankfurt werden in der site.conf pro Supernod-Peer zwei Remotes angegeben.

Beispiel aus https://github.com/freifunk-ffm/site-ffffm/blob/dev/site.conf :
```
groups =
backbone = {
        limit = 2,
        peers = {
          fastd1 = {
	    key = 'aaaaaaaaaaabbbbbbbbbbccccccccccccdddddddddddeeeeeeeffffffffff',
	    remotes = {'ipv4 "fastd1.ffm.freifunk.net" port 10001' , 'ipv4 "fastd1.ffm.freifunk.net" port 10002'},
	  },
```

Hinter den beiden Remote-Ports verbergen sich Supernode-fastd-Prozesse, welche auf unterschiedliche MTUs eingestellt sind.

Beim Verbindungsversuch werden die Supernode-Peer-Remotes nacheinander vom Router-fastd-Prozess durchprobiert.
Wenn dann mittels der eingestellten MTU über einen Supernode-fastd-Port eine Kommunikation möglich ist, so verbindet sich der Router mit dem Supernode.

Ob mehr als zwei Remotes möglich sind, ist mir nicht bekannt.
`limit = 2` hat nichts damit zu tun. Das wir in `fastd.mesh_vpn_backbone.peer_limit='2'` umgewandelt.

**Comment by oszilloskop** [comment]
Mehrere MTU-Grössen lassen sich mit wohl mit weiteren Peers, welche aber immer noch auf den gleichen Supernode zeigen,  realisieren.
Bsp.:
fastd1_MTU-Size_1-2
fastd1_MTU-Size_3-4

**Comment by christf** [comment]
On Sun, Apr 03, 2016 at 06:59:08PM -0700, oszilloskop wrote:
> Die Ports werden nicht in Abhängigkeit der MTU definiert.
> In Frankfurt werden in der site.conf pro Supernod-Peer zwei Remotes angegeben.

> Beispiel aus https://github.com/freifunk-ffm/site-ffffm/blob/dev/site.conf :

> groups =
> backbone = {
>         limit = 2,
>         peers = {
>           fastd1 = {
>         key = 'aaaaaaaaaaabbbbbbbbbbccccccccccccdddddddddddeeeeeeeffffffffff',
>         remotes = {'ipv4 "fastd1.ffm.freifunk.net" port 10001' , 'ipv4 "fastd1.ffm.freifunk.net" port 10002'},
>       },

> Hinter den beiden Remote-Ports verbergen sich Supernode-fastd-Prozesse, welche
> auf unterschiedliche MTUs eingestellt sind.

> Beim Verbindungsversuch werden die Supernode-Peer-Remotes nacheinander vom
> Router-fastd-Prozess durchprobiert.
> Wenn dann mittels der eingestellten MTU über einen Supernode-fastd-Port eine
> Kommunikation möglich ist, so verbindet sich der Router mit dem Supernode.

> Ob mehr als zwei Remotes möglich sind, ist mir nicht bekannt.
> limit = 2 hat nichts damit zu tun. Das wir in
> fastd.mesh_vpn_backbone.peer_limit='2' umgewandelt.
mehr als 2 peers sind möglich, im Node-Netz allerdings nicht sinnvoll.
Viele Communities arbeiten sogar nur mit einer Verbindung.

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments
