### ISSUE TITLE
ffffm-additional-wifi-json-info - wifi devices interchanged on dual band routers

### ISSUE THREAD

**Issue by TomSiener** [freifunk-ffm/packages#34]
On most dualband routers the radio0 device ist the 5Ghz Wifi device.

Thereefore the wifi infos from the 2,4 Ghz device are shown as 5Ghz and vice versa.

![image](https://user-images.githubusercontent.com/22204178/31273381-a9163ee4-aa8e-11e7-8e65-bec178b188de.png)

**Comment by oszilloskop** [comment]
Dieses Package ist nun obsolete. 
40098e23e34d2448d32505c3c90eac8e43067641
