### ISSUE TITLE
Anpassung notwendiger Gluon-Packages an neue Build-Umgebung (LEDE)

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/packages#35]
Für die Gluon-Umstellung von OpenWrt (bis Gluon 2016.x) auf LEDE (ab Gluon v2017.x) müssen die eigenen frankfurter Packages angepasst werden. 

Folgende Packages sollen evtl. weiterhin verwendet werden und benötigen daher eine Anpassung:
- [x] [ffffm-additional-wifi-json-info](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-additional-wifi-json-info)  (**Wird nicht mehr benötigt, Gluon 2017.x hat alles notwendige an Bord**)
- [x] [ffffm-ath9k-broken-wifi-workaround](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-ath9k-broken-wifi-workaround)
- [x] [ffffm-autoupdater-use-site-conf-branch](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-autoupdater-use-site-conf-branch) - bereits durch @christf umgesetzt
- [x] [ffffm-banner](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-banner) - bereits durch @christf umgesetzt
- [x] [ffffm-ebtables-net-rules](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-ebtables-net-rules) (mit LEDE noch notwendig?)(**Wird nicht mehr benötigt, Gluon 2017.x hat alles notwendige an Bord**)
- [x] [ffffm-keep-radio-channel](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-keep-radio-channel) (Untersuchung läuft noch, siehe [hier](http://gluon.readthedocs.io/en/stable/features/wlan-configuration.html?highlight=channel#wlan-configuration). (Update: Neue Umsetzung ist [fertig](https://github.com/freifunk-ffm/packages/commit/af9cdef8beca39fea49ef4ffa3fa99b5ca489cfd).) - bereits durch @christf umgesetzt
- [x] [ffffm-restart-respondd](https://github.com/freifunk-ffm/packages/tree/christf_lede/ffffm-restart-respondd) (wahrscheinlich nicht mehr notwendig)
- [x] [ffffm-button-bind](https://github.com/freifunk-ffm/packages/tree/master/ffffm-button-bind)

~~Die Anpassungen finden in dem Branch [christf_lede](https://github.com/freifunk-ffm/packages/tree/christf_lede) statt.~~

**Comment by christf** [comment]
ich denke wir haben alles.....

**Comment by oszilloskop** [comment]
ffffm-ath9k-broken-wifi-workaround muss ich mir nochmal ansehen. Das ist Batman-lastig.

**Comment by oszilloskop** [comment]
Alles ist umgestellt.

**Comment by oszilloskop** [comment]
Reminder:
Mit dem Gluon-Master, von Anfang August, gibt es Probleme mit dem Package "ffffm-keep-radio-channel".

`/usr/bin/lua: ./110-preserve-wireless-channels:4: module 'gluon.site_config' not found:
no field package.preload['gluon.site_config']
no file './gluon/site_config.lua'
no file '/usr/share/lua/gluon/site_config.lua'
no file '/usr/share/lua/gluon/site_config/init.lua'
no file '/usr/lib/lua/gluon/site_config.lua'
no file '/usr/lib/lua/gluon/site_config/init.lua'
no file './gluon/site_config.so'
no file '/usr/lib/lua/gluon/site_config.so'
...`


Unter Gluon 2018.1 gibt es hingegen keine Probleme.

**Comment by oszilloskop** [comment]
Nun sollten alle Package auch wieder unter OpenWrt funktionieren.
