### ISSUE TITLE
ath9k-broken-wifi-workaround.sh startet interface ständig neu

### ISSUE THREAD

**Issue by ctr49** [freifunk-ffm/packages#36]
Auf einem Testrouter (kein Wifi client, nur Ethernet) kommt ständig
```
Thu Jan  4 21:52:07 2018 user.notice root: ath9k-broken-wifi-workaround: Can't ping default gateway 86:9d:43:62:d7:50
Thu Jan  4 21:52:07 2018 user.notice root: ath9k-broken-wifi-workaround: No path to the default gateway 86:9d:43:62:d7:50
Thu Jan  4 21:52:07 2018 user.notice root: ath9k-broken-wifi-workaround: Wifi restart is pending
Thu Jan  4 21:54:20 2018 user.notice root: ath9k-broken-wifi-workaround: Can't ping default gateway 86:9d:43:62:d7:50
Thu Jan  4 21:54:20 2018 user.notice root: ath9k-broken-wifi-workaround: No path to the default gateway 86:9d:43:62:d7:50
Thu Jan  4 21:54:20 2018 user.notice root: ath9k-broken-wifi-workaround: *** Wifi restarted ***
```

Die Tests scheinen nicht zu beachten, dass es ja auch normal sein könnte, das wirklich kein Wifi Client verbunden ist...

**Comment by oszilloskop** [comment]
Wir haben da bereits vorhin drüber geredet.
Ich gebe Dir recht, bei isolierten und reinen Up-Link Routern ist das Verhalten suboptimal.

**Comment by oszilloskop** [comment]
Aktuell wird zuerst abgeprüft, ob überhaupt Client- bzw. Mesh-Verbindungen vorhanden sind/waren. Erst dann wird ggf. auf Client- bzw. Mesh-Verlust geprüft und entsprechend reagiert.

@ctr49 
Wenn nichts dagegen spricht, dann wird der Issue hier demnächst geschlossen.
