### ISSUE TITLE
Enhance readme ;)

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#39]
What do you mean with that big message "Do not use branches"? 

I think that is outdated, isnt it?

Please add a small description for each package, for example like we did it here: https://github.com/eulenfunk/packages/tree/v2018.1.x

**Comment by oszilloskop** [comment]
"Do not use branches" kann evtl. veraltet sein. Müsste man sich mal mit auseinander setzen. Schaden tut dieser Hinweis aber auf jeden Fall nicht.

Übergreifende und damit redundante Dokumentation sollten wir nicht anfangen, weil die würde nicht gepflegt werden. Viele der Packages haben aber eigene READM.md (ob die aktuell sind, dass ist ein anderes Thema).
