### ISSUE TITLE
ffffm-button-bind: Doesn't work in 2018.1

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#40]
I tested this with your master branch on a 841N-v7: "Nachtmodus"

in config mode, the Buttan has no effect. And in normal mode also no effect.

I think the internal button values in the filesystem somehow changed in 2018.1

**Comment by rubo77** [comment]
- https://github.com/freifunk-ffm/packages branch master

- gluon tag 2018.1

**Comment by oszilloskop** [comment]
Was sagt site/modules ?

**Comment by rubo77** [comment]
https://github.com/freifunk-Kiel/ffki-site

**Comment by rubo77** [comment]
1043v4 works fine, so it seems it is only a problem with the 841v7.

we will remove the package from that model then here: https://github.com/freifunk-kiel/site-ffki/blob/nightly/site.mk#L202

**Comment by rubo77** [comment]
Maybe you can add your experiences in our test-ticket: https://github.com/rubo77/ffm-packages/issues/2

**Comment by oszilloskop** [comment]
Das wird schwer, weil unsere Module doch schon etwas auseinander gedriftet sind.
Hier aber meine Erfahrung:
WR1043v2: Funktioniert, die WAN-LED wird aber nicht mehr eingeschaltet.
WR841v9 + v10: Funktioniert alles.
