### ISSUE TITLE
button-bind: wifi reset erweitern

### ISSUE THREAD

**Issue by rubo77** [freifunk-ffm/packages#44]
AUsserdem könnte der taster in dem moment einmal 

`batctl gw off; batctl gw client 1`

ausführen um das optimale gateway auswählen zu lassen

**Comment by rubo77** [comment]
Es ist ja oft so, dass ein router ei gateway gewählt hat, welches nicht das jenige ist, welches der router, der den uplink bereitstellt gewählt hat. dadurch entsteht inter-gateway traffic. Mit dem Befehlt handelt Batman die routen neu aus und wählt automatisch das nächste GW

**Comment by rubo77** [comment]
So haben wir das gelöst: 

https://github.com/rubo77/ffm-packages/commit/6fbd501ac1aeb2be76780fd8c43dd7ee4bc4ba10

**Comment by oszilloskop** [comment]
Die Weiterentwicklung dieses Packages wird von @rubo77 in https://github.com/rubo77/ffm-packages durchgeführt.
