### ISSUE TITLE
v4up timeout

### ISSUE THREAD

**Issue by MyIgel** [freifunk-ffm/packages#9]
Aktuell braucht das v4up-script > 3min. um eine IP zu bekommen
* Timeout für wget implementieren

**Comment by oszilloskop** [comment]
In dem [Skript v4up](https://github.com/freifunk-ffm/packages/blob/master/ffffm-banner/files/usr/bin/v4up) wird testweise auf einen Server mit IPv4 zugegriffen. Jetzt ist dieser Server aber wohl auch über IPv6 zu erreichen. Das BusyBox "wget" hat da extremste Probleme mit.

Daher sollte in dem Skript nicht mehr http://ffm.freifunk.net sondern http://httpbin.org/ip verwendet werden.

**Comment by oszilloskop** [comment]
Oder wir nehmen, wie @MyIgel  vorschlägt, einen Servernamen, der von unserer Kontrolle werden kann. Zum Beispiel : http://v4.ffm.freifunk.net 
Das ganze sollte dann aber gut dokumentiert werden.

**Comment by MyIgel** [comment]
V4 ist angelegt & kann verwendet werden

**Comment by oszilloskop** [comment]
Fix siehe 3a237fd
